# Generated by Django 2.2.18 on 2021-09-08 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='Email',
        ),
    ]
